name: Stock Pipeline

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Stock Simulator
        run: timeout 30 python stock_simulator.py || true

      - name: Run ETL Pipeline
        run: python etl_pipeline.py

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: stock-data
          path: |
            stock_log.json
            stock_warehouse.db